import Head from "next/head";
import { Box } from "@chakra-ui/react";

import AppLayout from "@/layout/app-layout";
import { Chat } from "@roq/nextjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Box w="100%" h="80vh">
          <Chat fluid={true} />
        </Box>
      </AppLayout>
    </>
  );
}
