import { useState } from "react";
import Head from "next/head";
import Editor from "@monaco-editor/react";
import AppLayout from "@/layout/app-layout";
import { Card, Flex, Box, Button } from "@chakra-ui/react";

export default function CodeConverter() {
  const [result, setResult] = useState("");
  const [inputCode, setInputCode] = useState<string>();
  const [loading, setLoading] = useState(false);

  const handleConvert = async () => {
    if (!inputCode) {
      return;
    }
    setLoading(true);
    const result = await fetch("/api/convert", {
      method: "POST",
      headers: { "Content-Type": "application/json" },

      body: JSON.stringify({ code: inputCode }),
    });

    const pythonCode = await result.json();
    console.log(pythonCode);
    setLoading(false);
    setResult(pythonCode.code);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <Flex gap="30px">
          <Box w="50%">
            <Editor
              theme="dark"
              height="85vh"
              defaultLanguage="javascript"
              defaultValue="// Enter javascript here"
              onChange={(value) => setInputCode(value)}
            />

            <Button onClick={handleConvert}>Convert</Button>
          </Box>
          <Box w="50%">
            <Editor
              theme="dark"
              height="85vh"
              language="python"
              value={result}
              loading={loading}
              defaultValue="# Output python here"
            />
          </Box>
        </Flex>
      </AppLayout>
    </>
  );
}
