import Head from "next/head";
import Board from "react-trello-ts";
import { boardData } from "./data";
import AppLayout from "@/layout/app-layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        {boardData ? (
          <Board
            style={{ background: "#FFF" }}
            data={boardData}
            draggable
            id="EditableBoard1"
            hideCardDeleteAction={false}
            editable
            canAddLanes
            editLaneTitle
          />
        ) : (
          <></>
        )}
      </AppLayout>
    </>
  );
}
